export const UPDATE_HOME_AIRPORT = 'UPDATE_HOME_AIRPORT';
export const UPDATE_HOME_TRACKERS = 'UPDATE_HOME_TRACKERS';
export const UPDATE_HOME_TRACKERS_STATUS = 'UPDATE_HOME_TRACKERS_STATUS';
export const UPDATE_HOME_SINGLE_TRACKER = 'UPDATE_HOME_SINGLE_TRACKER';